/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kafka.common.message;

import org.apache.kafka.common.protocol.ByteBufferAccessor;
import org.apache.kafka.common.protocol.Message;
import org.apache.kafka.common.protocol.MessageUtil;
import org.junit.jupiter.api.Test;

import java.nio.ByteBuffer;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Wire fixtures generated by serializing the matching data objects from the compiled Kafka 3.9-li bridge.
 */
public class BridgeControlProtocolFixtureTest {
    private static final byte[] LEADER_AND_ISR_V2 = bytes(
        "000000070000000800000000000000090000000100066f7264657273000000010000000300000008" +
            "00000002000000040000000200000002000000030000000500000003000000020000000300000004" +
            "010000000100000002000662726f6b657200002384");
    private static final byte[] UPDATE_METADATA_V5 = bytes(
        "000000070000000800000000000000090000000100066f7264657273000000010000000300000008" +
            "00000002000000040000000200000002000000030000000500000003000000020000000300000004" +
            "000000010000000400000001000000020000000100002384000662726f6b6572000353534c00010006" +
            "7261636b2d61");
    private static final byte[] STOP_REPLICA_V1 = bytes(
        "00000007000000080000000000000009010000000100066f7264657273000000020000000300000004");

    @Test
    public void testLeaderAndIsrV2Fixture() {
        LeaderAndIsrRequestData data = new LeaderAndIsrRequestData(
            new ByteBufferAccessor(ByteBuffer.wrap(LEADER_AND_ISR_V2)), (short) 2);
        assertControlHeader(data.controllerId(), data.controllerEpoch(), data.brokerEpoch());
        assertEquals("orders", data.topicStates().get(0).topicName());
        assertEquals(3, data.topicStates().get(0).partitionStates().get(0).partitionIndex());
        assertEquals(5, data.topicStates().get(0).partitionStates().get(0).zkVersion());
        assertEquals(2, data.liveLeaders().get(0).brokerId());
        assertEquals("broker", data.liveLeaders().get(0).hostName());
        assertFixture(LEADER_AND_ISR_V2, data, (short) 2);
    }

    @Test
    public void testUpdateMetadataV5Fixture() {
        UpdateMetadataRequestData data = new UpdateMetadataRequestData(
            new ByteBufferAccessor(ByteBuffer.wrap(UPDATE_METADATA_V5)), (short) 5);
        assertControlHeader(data.controllerId(), data.controllerEpoch(), data.brokerEpoch());
        assertEquals("orders", data.topicStates().get(0).topicName());
        assertEquals(3, data.topicStates().get(0).partitionStates().get(0).partitionIndex());
        assertEquals(4, data.topicStates().get(0).partitionStates().get(0).offlineReplicas().get(0));
        assertEquals("rack-a", data.liveBrokers().get(0).rack());
        assertFixture(UPDATE_METADATA_V5, data, (short) 5);
    }

    @Test
    public void testStopReplicaV1Fixture() {
        StopReplicaRequestData data = new StopReplicaRequestData(
            new ByteBufferAccessor(ByteBuffer.wrap(STOP_REPLICA_V1)), (short) 1);
        assertControlHeader(data.controllerId(), data.controllerEpoch(), data.brokerEpoch());
        assertTrue(data.deletePartitions());
        assertEquals("orders", data.topics().get(0).name());
        assertEquals(3, data.topics().get(0).partitionIndexes().get(0));
        assertEquals(4, data.topics().get(0).partitionIndexes().get(1));
        assertFixture(STOP_REPLICA_V1, data, (short) 1);
    }

    private static void assertControlHeader(int controllerId, int controllerEpoch, long brokerEpoch) {
        assertEquals(7, controllerId);
        assertEquals(8, controllerEpoch);
        assertEquals(9L, brokerEpoch);
    }

    private static void assertFixture(byte[] expected, Message message, short version) {
        ByteBuffer buffer = MessageUtil.toByteBuffer(message, version);
        byte[] actual = new byte[buffer.remaining()];
        buffer.get(actual);
        assertArrayEquals(expected, actual);
    }

    private static byte[] bytes(String hex) {
        byte[] result = new byte[hex.length() / 2];
        for (int i = 0; i < result.length; i++) {
            result[i] = (byte) Integer.parseInt(hex.substring(i * 2, i * 2 + 2), 16);
        }
        return result;
    }
}
